/* **************************************************************** */
/* ******************name:/ Mohanad Mohamed ************************/
/* ******************date:8.6.2023******************************* */
/* ******************version:/ 1.0****************************** */
/* ************************************************************ */
#ifndef config
#define config

/****************MACROS FOR INTIAL DIRECTOPN***********/

#define DIO_u8_PORTA_PIN0_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN1_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN2_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN3_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN4_INITIAL_DIRECTION DIO_u8_INPUT
#define DIO_u8_PORTA_PIN5_INITIAL_DIRECTION DIO_u8_INPUT
#define DIO_u8_PORTA_PIN6_INITIAL_DIRECTION DIO_u8_INPUT
#define DIO_u8_PORTA_PIN7_INITIAL_DIRECTION DIO_u8_INPUT

#define DIO_u8_PORTB_PIN0_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN1_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN2_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN3_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN4_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN5_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN6_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN7_INITIAL_DIRECTION DIO_u8_OUTPUT

#define DIO_u8_PORTC_PIN0_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN1_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN2_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN3_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN4_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN5_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN6_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN7_INITIAL_DIRECTION DIO_u8_OUTPUT

#define DIO_u8_PORTD_PIN0_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN1_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN2_INITIAL_DIRECTION DIO_u8_PIN_INPUT
#define DIO_u8_PORTD_PIN3_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN4_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN5_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN6_INITIAL_DIRECTION DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN7_INITIAL_DIRECTION DIO_u8_OUTPUT

/*******MACROPS FOR INTIAL VALUES*********/

#define DIO_u8_PORTA_PIN0_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTA_PIN1_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTA_PIN2_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTA_PIN3_INITIAL_VALUE		DIO_u8_HIGH
#define DIO_u8_PORTA_PIN4_INITIAL_VALUE		DIO_u8_PULL_UP
#define DIO_u8_PORTA_PIN5_INITIAL_VALUE		DIO_u8_PULL_UP
#define DIO_u8_PORTA_PIN6_INITIAL_VALUE		DIO_u8_PULL_UP
#define DIO_u8_PORTA_PIN7_INITIAL_VALUE		DIO_u8_PULL_UP

#define DIO_u8_PORTB_PIN0_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN1_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN2_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN3_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN4_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN5_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN6_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTB_PIN7_INITIAL_VALUE		DIO_u8_LOW

#define DIO_u8_PORTC_PIN0_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN1_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN2_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN3_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN4_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN5_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN6_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTC_PIN7_INITIAL_VALUE		DIO_u8_LOW

#define DIO_u8_PORTD_PIN0_INITIAL_VALUE		DIO_u8_PULL_UP
#define DIO_u8_PORTD_PIN1_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTD_PIN2_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTD_PIN3_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTD_PIN4_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTD_PIN5_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTD_PIN6_INITIAL_VALUE		DIO_u8_LOW
#define DIO_u8_PORTD_PIN7_INITIAL_VALUE		DIO_u8_LOW

#endif
