# Compiler
CXX = g++


# Source files
SRCS = main.cpp BookClass.cpp

# Executable name
EXEC = library

# Target: Build the executable
$(EXEC): $(SRCS)
	$(CXX) $(SRCS) -o $(EXEC)

# Target: Clean up
clean:
	rm -f $(EXEC)
